/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace fizenpay_auth {
	export interface RoleService {
		checkPermission(
			data: CheckPermissionRequest,
			metadata?: Metadata,
		): Observable<CheckPermissionResponse>;
		reloadPolicy(
			data: ReloadPolicyRequest,
			metadata?: Metadata,
		): Observable<ReloadPolicyResponse>;
		getRolesByEmail(
			data: GetRolesByEmailRequest,
			metadata?: Metadata,
		): Observable<GetRolesByEmailResponse>;
		getUsersByRole(
			data: GetUsersByRoleRequest,
			metadata?: Metadata,
		): Observable<GetUsersByRoleResponse>;
	}
	export interface GetUsersByRoleRequest {
		domain?: string;
		role?: string;
	}
	export interface GetUsersByRoleResponse {
		users?: fizenpay_auth.UserRole[];
	}
	export interface UserRole {
		email?: string;
		role?: string;
	}
	export interface CheckPermissionRequest {
		email?: string;
		path?: string;
		domain?: string;
		method?: string;
	}
	export interface CheckPermissionResponse {
		hasPermission?: boolean;
	}
	// tslint:disable-next-line:no-empty-interface
	export interface ReloadPolicyRequest {}
	// tslint:disable-next-line:no-empty-interface
	export interface ReloadPolicyResponse {}
	export interface GetRolesByEmailRequest {
		email?: string;
		domain?: string;
	}
	export interface GetRolesByEmailResponse {
		roles?: string[];
	}
}
