/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace fizenpay_be {
    export interface SettingService {
        findAllSupportedChain(data: Empty, metadata?: Metadata): Observable<ListSupportedChain>;
        createSupportedChain(data: SupportedChain, metadata?: Metadata): Observable<ListSupportedChain>;
        updateSupportedChain(data: UpdateSupportedChainRequest, metadata?: Metadata): Observable<UpdateSupportedChainResponse>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
    export interface SupportedChain {
        bip44Path?: string;
        currency?: string;
        isMainnet?: boolean;
        network?: string;
        provider?: string;
        wssProvider?: string;
        fpMasterContract?: string;
        transactionUrl?: string;
    }
    export interface ListSupportedChain {
        items?: fizenpay_be.SupportedChain[];
        total?: number;
    }
    export interface UpdateSupportedChainRequest {
        bip44Path?: string;
        currency?: string;
        isMainnet?: boolean;
        network?: string;
        provider?: string;
        wssProvider?: string;
        fpMasterContract?: string;
        transactionUrl?: string;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface UpdateSupportedChainResponse {
    }
}

