/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace fizenpay_be {
    export interface SettingsService {
        findAllSupportedChains(data: Empty, metadata?: Metadata): Observable<SupportedChainsResponse>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
    export interface SupportedChainsResponse {
        bip44Path?: string;
        currency?: string;
        isMainnet?: boolean;
        network?: string;
        provider?: string;
        wssProvider?: string;
        fpMasterContract?: string;
        transactionUrl?: string;
    }
}

