/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace fizenpay_be {
    export interface SettingsService {
        findAllSupportedChain(data: Empty, metadata?: Metadata): Observable<ListSupportedChains>;
        createSupportedChain(data: SupportedChains, metadata?: Metadata): Observable<ListSupportedChains>;
        updateSupportedChain(data: UpdateSupportedChainRequest, metadata?: Metadata): Observable<UpdateSupportedChainResponse>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
    export interface SupportedChains {
        bip44Path?: string;
        currency?: string;
        isMainnet?: boolean;
        network?: string;
        provider?: string;
        wssProvider?: string;
        fpMasterContract?: string;
        transactionUrl?: string;
    }
    export interface ListSupportedChains {
        chains?: fizenpay_be.SupportedChains[];
    }
    export interface UpdateSupportedChainRequest {
        bip44Path?: string;
        currency?: string;
        isMainnet?: boolean;
        network?: string;
        provider?: string;
        wssProvider?: string;
        fpMasterContract?: string;
        transactionUrl?: string;
    }
    export interface UpdateSupportedChainResponse {
        affected?: number;
    }
}

