/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace blockchain_service {
	export interface OWActiveStatusHistoryService {
		findAll(
			data: FindAllOWActiveStatusHistoriesRequest,
			metadata?: Metadata,
		): Observable<FindAllOWActiveStatusHistoriesResponse>;
	}
	export interface FindAllOWActiveStatusHistoriesRequest {
		changedActiveStatus?: string;
		address?: string;
		page?: number;
		limit?: number;
	}
	export interface FindAllOWActiveStatusHistoriesResponse {
		owActiveStatusHistories?: blockchain_service.OWActiveStatusHistory[];
		total?: number;
	}
	export interface OWActiveStatusHistory {
		id?: string;
		owID?: string;
		address?: string;
		activeStatus?: string;
		changedActiveStatus?: string;
		createdAt?: string;
		updatedAt?: string;
	}
}
