/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace blockchain_service {
    export interface OperatorTransactionProto {
        getTransactions(data: GetTransactionsRequest, metadata?: Metadata): Observable<GetTransactionsResponse>;
    }
    export interface GetTransactionsRequest {
        operatorAddress?: string;
        page?: number;
        limit?: number;
        event?: string;
        from?: string;
        to?: string;
        hash?: string;
        merchantContract?: string;
    }
    export interface GetTransactionsResponse {
        transactions?: blockchain_service.TransactionHistory[];
        total?: number[];
    }
    export interface TransactionHistory {
        id?: string;
        rawData?: google.protobuf.Any;
        details?: google.protobuf.Any;
        receiptLogs?: google.protobuf.Any;
        tokenInfo?: google.protobuf.Any;
        methodName?: string;
        hash?: string;
        network?: string;
        blockTimestamp?: google.protobuf.Timestamp;
        blockNumber?: string;
        blockHash?: string;
        inputHash?: string;
        operator?: string;
        merchantContract?: string;
        from?: string;
        to?: string;
        createdAt?: google.protobuf.Timestamp;
        updatedAt?: google.protobuf.Timestamp;
    }
}
export namespace google {
    export namespace protobuf {
        export interface Any {
            type_url?: string;
            value?: Uint8Array;
        }
        export interface Timestamp {
            seconds?: number;
            nanos?: number;
        }
    }
}

