/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace blockchain_service {
    export interface OperatingWalletService {
        findAll(data: FindAllOWRequest, metadata?: Metadata): Observable<FindAllOWResponse>;
        getNetworkSettings(data: Empty, metadata?: Metadata): Observable<GetNetworkSettingsResponse>;
        updateNetworkSettings(data: UpdateNetworkSettingsRequest, metadata?: Metadata): Observable<Empty>;
        batchImport(data: BatchImportRequest, metadata?: Metadata): Observable<BatchImportResponse>;
        getMasterOperatingWallet(data: GetMasterOperatingWalletRequest, metadata?: Metadata): Observable<GetMasterOperatingWalletResponse>;
        createChainSettings(data: CreateChainSettingsRequest, metadata?: Metadata): Observable<CreateChainSettingsResponse>;
        updateChainSettings(data: UpdateChainSettingsRequest, metadata?: Metadata): Observable<UpdateChainSettingsResponse>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
    // tslint:disable-next-line:no-empty-interface
    export interface FindAllOWRequest {
    }
    export interface FindAllOWResponse {
        operatingWallets?: blockchain_service.OperatingWallet[];
    }
    export interface OperatingWallet {
        id?: string;
        name?: string;
        index?: number;
        activeStatus?: string;
        commandStatus?: string;
        createdAt?: string;
        updatedAt?: string;
        address?: string;
    }
    export interface GetNetworkSettingsResponse {
        networks?: blockchain_service.OWNetworkSettings[];
    }
    export interface GetMasterOperatingWalletResponse {
        publicKey?: string;
        privateKey?: string;
    }
    export interface GetMasterOperatingWalletRequest {
        network?: string;
    }
    export interface OWNetworkSettings {
        network?: string;
        currency?: string;
        isMainnet?: boolean;
        networkId?: string;
        masterOperatingWallet?: string;
        masterOperatingWalletThreshold?: string;
        autoTopupStatus?: string;
        autoTopupThreshold?: string;
        autoTopupAmount?: string;
    }
    export interface UpdateNetworkSettingsRequest {
        network?: string;
        autoTopupThreshold?: string;
        autoTopupAmount?: string;
    }
    export interface CreateChainSettingsRequest {
        network?: string;
        currency?: string;
        isMainnet?: boolean;
        networkId?: string;
        provider?: string;
        wssProvider?: string;
        fpMasterContract?: string;
        transactionUrl?: string;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface CreateChainSettingsResponse {
    }
    export interface UpdateChainSettingsRequest {
        network?: string;
        currency?: string;
        isMainnet?: boolean;
        networkId?: string;
        provider?: string;
        wssProvider?: string;
        fpMasterContract?: string;
        transactionUrl?: string;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface UpdateChainSettingsResponse {
    }
    export interface BatchImportRequest {
        wallets?: blockchain_service.Wallet[];
    }
    // tslint:disable-next-line:no-empty-interface
    export interface BatchImportResponse {
    }
    export interface Wallet {
        address?: string;
        privateKey?: string;
    }
}

