/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace event_consumer {
    export interface WebhookService {
        getOne(data: GetOneRequest, metadata?: Metadata): Observable<ChargeResponse>;
    }
    export interface GetOneRequest {
        id?: string;
    }
    export interface ChargeResponse {
        id?: string;
        name?: string;
        description?: string;
        pricingType?: string;
        redirectUrl?: string;
        cancelUrl?: string;
        userId?: string;
        status?: string;
    }
}
export namespace google {
    export namespace protobuf {
        export interface Timestamp {
            seconds?: number;
            nanos?: number;
        }
    }
}

