/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace event_consumer {
    export interface WebhookService {
        findOne(data: WebhookById, metadata?: Metadata): Observable<WebhookResponse>;
    }
    export interface WebhookById {
        id?: number;
    }
    export interface WebhookResponse {
        id?: number;
        name?: string;
    }
}

