/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace event_consumer {
	export interface WebhookService {
		subscribeWebhook(
			data: SubscribeWebhookRequest,
			metadata?: Metadata,
		): Observable<SubscribeWebhookResponse>;
		subscribeWebhooks(
			data: SubscribeWebhooksRequest,
			metadata?: Metadata,
		): Observable<SubscribeWebhooksResponse>;
		findAllTypes(
			data: Empty,
			metadata?: Metadata,
		): Observable<WebhooksResponse>;
		findAll(
			data: FindAllRequest,
			metadata?: Metadata,
		): Observable<FindAllResponse>;
		unsubscribeWebhook(
			data: UnsubscribeWebhookRequest,
			metadata?: Metadata,
		): Observable<UnsubscribeWebhookResponse>;
		unsubscribeWebhooks(
			data: UnsubscribeWebhooksRequest,
			metadata?: Metadata,
		): Observable<UnsubscribeWebhooksResponse>;
		updateEndpoint(
			data: UpdateEndpointRequest,
			metadata?: Metadata,
		): Observable<UpdateEndpointResponse>;
		sendTest(
			data: SendTestRequest,
			metadata?: Metadata,
		): Observable<SendTestResponse>;
	}
	export interface FindAllRequest {
		merchantId?: string;
	}
	export interface FindAllResponse {
		urls?: event_consumer.UrlsResponse[];
	}
	export interface UrlsResponse {
		url?: string;
		webhooks?: event_consumer.WebhookResponse[];
	}
	export interface SubscribeWebhookRequest {
		merchantId?: string;
		webhookId?: string;
		url?: string;
	}
	export interface SubscribeWebhookResponse {
		merchantId?: string;
		webhook?: event_consumer.WebhookResponse;
	}
	export interface SubscribeWebhooksRequest {
		merchantId?: string;
		url?: string;
	}
	export interface SubscribeWebhooksResponse {
		merchantId?: string;
		webhooks?: event_consumer.WebhookResponse[];
	}
	export interface UnsubscribeWebhookRequest {
		merchantId?: string;
		webhookId?: string;
		url?: string;
	}
	export interface WebhookResponse {
		id?: string;
		topic?: string;
		urls?: string[];
		isSubscribed?: boolean;
	}
	export interface WebhooksResponse {
		webhooks?: event_consumer.WebhookResponse[];
	}
	// tslint:disable-next-line:no-empty-interface
	export interface UnsubscribeWebhookResponse {}
	export interface UpdateEndpointRequest {
		merchantId?: string;
		webhooks?: event_consumer.WebhookUpdateEndpointRequest[];
		url?: string;
	}
	// tslint:disable-next-line:no-empty-interface
	export interface UpdateEndpointResponse {}
	export interface WebhookUpdateEndpointRequest {
		topic?: string;
		isSubscribed?: boolean;
	}
	export interface SendTestRequest {
		topic?: string;
		merchantId?: string;
		url?: string;
		sharedSecret?: string;
	}
	export interface SendTestResponse {
		status?: string;
		responseBody?: string;
	}
	export interface UnsubscribeWebhooksRequest {
		merchantId?: string;
		url?: string;
	}
	// tslint:disable-next-line:no-empty-interface
	export interface UnsubscribeWebhooksResponse {}
	// tslint:disable-next-line:no-empty-interface
	export interface Empty {}
}
export namespace google {
	export namespace protobuf {
		export interface Timestamp {
			seconds?: number;
			nanos?: number;
		}
	}
}
