/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace fizen_admin_api {
    export interface AdminTokenService {
        verifyAdminToken(data: VerifyAdminTokenRequest, metadata?: Metadata): Observable<VerifyAdminTokenResponse>;
    }
    export interface VerifyAdminTokenRequest {
        token?: string;
    }
    export interface VerifyAdminTokenResponse {
        id?: string;
        email?: string;
        firstName?: string;
        lastName?: string;
        createdAt?: string;
        updatedAt?: string;
        lastLoginAt?: string;
    }
}
export namespace google {
    export namespace protobuf {
        export interface Timestamp {
            seconds?: number;
            nanos?: number;
        }
    }
}

